- name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          ./gradlew ensureJarCompatibility
          cp -f **/build/*.cs3 $GITHUB_WORKSPACE/builds/ || true
          cp -f **/build/*.jar $GITHUB_WORKSPACE/builds/ || true
          cp -f build/plugins.json $GITHUB_WORKSPACE/builds/plugins.json

      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A
          git commit -m "Force update plugins.json" || exit 0
          git push --force origin builds
